wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699263529.546048
    t:
      1:
      - 1
      - 55
      - 95
      2:
      - 1
      - 55
      - 95
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
