name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download wallets
        run: aws s3 sync s3://$WALLET_BUCKET ~/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          WALLET_BUCKET: ${{ secrets.WALLET_BUCKET }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install nox
        run: python -m pip install --upgrade nox pip setuptools
      - name: Install dependencies
        run: nox -s install_test_requirements
      - name: Run tests
        run: PYTHONPATH=$PWD pytest tests/weights -rP -vv  # integration tests hang in CI for some reason
        env:
          RICH_TRACEBACK: 0
          CORTEXT_MINER_ADDITIONAL_WHITELIST_VALIDATOR_KEYS: ${{ secrets.VALIDATOR_KEY }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STABILITY_KEY: ${{ secrets.STABILITY_KEY }}
